export var menulist = ["idly",
"biscut",
"sambar idly",
"vadai",
"curd vadai",
"sambar vadai",
"poori",
"pongal",
"paper roast",
"oninon dosa",
"onion uthappam",
"podi dosa",
"rava dosa",
"onion rava dosa",
"plain dosa",
"ghee dosa",
"masala  dosa",
"mushroom masala dosa",
"paneer dosa",
"chola poori",
"chappathi",
"parotta",
"kichadi",
"kothu parotta",
"idiyappam",
"kuzhi paniyaram",
"mini tiffin",
"meals",
"spl.meals",
"variety rice",
"veg biriyani",
"mushroom biriyani",
"veg rice",
"veg noodles ",
"gobi rice",
"gobi nooodles",
"mushroom rice",
"mushroom noodles",
"paneer rice",
"paneer noodles",
"mixed rice",
"mixed noodles", 
"gobi 65",
"mushroom 65",
"paneer 65",
"gobi chilli",
"mushroom chilli",
"paneer chilli",
"gobi manjurian",
"mushroom manjurian",
"paneer manjurian",
"paneer butter masala",
"mushroom masala",
"chenna gravy",
"chilli parotta", 
"chilli idly", 
"idly fry",
"sezwan rice",
"sezwan noodles",
"baby corn manjurian",
"veg garlic soup",
"mensow soup", 
"samosa", 
"tea", 
"coffee",
"milk", 
"boost",
"horlicks", 
"badam milk", 
"p.candy.milk",
"jaggery milk",
"water bottle", 
"small water bottle", 
"sukku coffee",
"kal dosa", 
"extra rice",
"lemon tea",
"black tea",
"jaggery tea",
"pappad",  
"sundal",
"2lt water",
"keema parotta", 
"vazaipoo vada",
"bonda",
"kal podi dosa", 
"ghee podi dosa",
"parotta chenna",
"chappathi chenna",
"thinai pongal",
"varagu variety",
"small milet pongal",
"samba rava kichadi",
"gobi masala",
"horsetail pongal", 
"ghee rava roast",
"sweet",
"gobi pepper fry",
"mushroom pepper fry",
"paneer pepper fry",
"ghee podi onion dosa",
"kadai panner",
"ghee oninon dosa",
"onion podi uthappam",
"kal ghee dosa", 
"plain naan", 
"butter naan", 
"naan gravy",
"butter naan gravy",
"rotti gravy",
"butter rotti gravy",
"fulkha gravy",
"pulkha",
"rotti", 
"butter rotti", 
"seswan paneer rice", 
"seswan paneer noodles", 
"seswan mushroom rice", 
"seswan mushroom noodles", 
"seswan gobi rice", 
"seswan gobi noodles",
"butter rotti gravy", 
"onion pakkoda", 
"ghee masala dosa", 
"mixed veg gravy", 
"veg sandwitch", 
"veg cheese sandwitch", 
"mushroom sandwitch", 
"panner sandwitch", 
"gulab jaamun", 
"mushroom soup", 
"kozhukattai",
"rava laddu",
"aappam",
"badhusha",
"somas",
"karasev",
"halwa",
"vazaithandu soup",
"green peas masala",
"stuffed naan",
"garlic naan",
"jeera naan",
"panner naan",
"gobi naan",
"mushroom naan",
"masala kulcha", 
"stuffed kulcha",
"tandoori parotta"]

